FROM node:20-alpine

WORKDIR /app

COPY package*.json prisma.config.ts tsconfig.json ./
COPY prisma/ ./prisma/
COPY src/ ./src/
RUN npm ci

CMD ["sh", "-c", "npx prisma migrate deploy && npx prisma db seed"]
